spring.application.name=sis

spring.datasource.url=jdbc:mysql://localhost:3306/sis?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# IMPORTANT: remove old dialect warning
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect